name: angel_build_runner
version: 1.0.0
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_framework: ^2.0.0-alpha
  angel_shelf: ^2.0.0
  build_runner: ^1.0.0
dev_dependencies:
  build_config:
  build_web_compilers: ^0.4.0